title: Alzheimer Detection
emoji: 🧠
colorFrom: green
colorTo: pink
sdk: gradio
sdk_version: 5.46.1
app_file: app.py
pinned: false
python_version: "3.11"
license: apache-2.0
short_description: To detect Alzheimer based on ConvNeXt from brain MRI image