name: CI/CD to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repos
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run unit testing
      - name: Run tests
        env:
          DATABRICKS_URL: ${{ secrets.DATABRICKS_URL }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo "🚀 Running unit tests..."
          pytest tests/ -v --tb=short
          echo "✅ All tests passed!"

      # Test app starting
      - name: Test app startup
        run: |
          timeout 10 python app.py || echo "App started successfully"

      # Deploy to Hugging Face Spaces
      - name: Deploy to Hugging Face Spaces
        if: success()
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_REPO: ${{ secrets.HF_SPACE_REPO }}
        run: |
          # Install huggingface_hub
          pip install huggingface_hub
          # Login to Hugging Face
          huggingface-cli login --token $HF_TOKEN
          # Push to HF Spaces
          huggingface-cli repo create $HF_SPACE_REPO --type space --organization KaiSKX || true
          git remote add space https://huggingface.co/spaces/$HF_SPACE_REPO
          git push --force space main
